- name: Ensure python3 is available
  ansible.builtin.package:
    name: python3
  tags: deps

- name: Ensure pymongo is installed
  ansible.builtin.pip:
    name: pymongo==4.10.1
    state: present
  tags: deps

- name: Echo hostname
  ansible.builtin.debug:
    msg: "The ansible_hostname is: {{ ansible_hostname }}"
  tags: deps
