- name: Display the OS family
  ansible.builtin.debug:
    msg: "The OS family is: {{ ansible_os_family }}"
  tags: mongo_repo

- name: Add Mongodb repo file
  ansible.builtin.template:
    src: mongodb-org.repo.j2
    dest: "/etc/yum.repos.d/mongodb-org-{{ mongodb_version }}.repo"
    mode: "0644"
  become: true
  tags: mongo_repo
  when: ansible_os_family == "RedHat"
