- name: Add Mongodb repo file
  ansible.builtin.template:
    src: mongodb-org.repo.j2
    dest: "/etc/yum.repos.d/mongodb-org-{{ mongodb_version }}.repo"
    mode: "0644"
  become: true
  tags: mongodb

- name: Install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: present
  become: true
  tags: mongodb

# This checks if the word "inactive" is not present in
# the output (stdout) of the command. If it is not present,
# the task will fail.
- name: Check if mongodb is running
  ansible.builtin.command:
    cmd: systemctl is-active mongod
  register: result
  failed_when: result.rc != 0 and "inactive" not in result.stdout
  changed_when: false
  become: true
  tags:
    - mongodb-running
    - mongodb

- name: Debug MongoDB status
  ansible.builtin.debug:
    msg: "MongoDB is {{ result.stdout }}"
  tags:
    - mongodb-running
    - mongodb

- name: Start mongodb
  ansible.builtin.systemd:
    name: mongod
    state: started
    enabled: true
  become: true
  when: result.rc != 0 or result.stdout.find("inactive") == 1
  tags: mongodb

- name: Get hostname of current host
  ansible.builtin.shell: echo $HOSTNAME
  register: result_hostname
  changed_when: false
  tags: mongodb

- name: Update mongodb config file
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: "{{ result_hostname.stdout }}"
  become: true
  notify:
    - Restart Mongodb
  tags: mongodb

# Create a replicaset called 'rs0' with the 3 provided members
- name: Ensure replicaset rs0 exists
  community.mongodb.mongodb_replicaset:
    login_host: "{{ result_hostname.stdout }}"
    login_user: admin
    login_password: admin
    replica_set: rs0
    members:
      - broker03:27017
      - broker04:27017
      - broker05:27017
  become: true
  tags:
    - mongodb-rs0
    - mongodb
