all:
  vars:
    global:
      - any1
      - any2
  children:
    deploy_machines:
      hosts:
        broker03:
          ansible_host: broker03
          ansible_ssh_user: "nmaharaj"
          # Fails on arm64
          # ansible_ssh_private_key_file: "/Users/nmaharaj/.ssh/id_ed25519"
          ansible_ssh_private_key_file: '/Users/nmaharaj/Documents/ansible/private_key/id_ed25519'
          ansible_private_key_file: /Users/nmaharaj/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python
          ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
        broker04:
          ansible_host: broker04
          ansible_ssh_user: nmaharaj
          # Fails on arm64
          # ansible_ssh_private_key_file: "/Users/nmaharaj/.ssh/id_ed25519"
          ansible_ssh_private_key_file: '/Users/nmaharaj/Documents/ansible/private_key/id_ed25519'
          ansible_python_interpreter: /usr/bin/python
          ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
        broker05:
          ansible_host: broker05
          ansible_ssh_user: nmaharaj
          # Fails on arm
          # ansible_ssh_private_key_file: "/Users/nmaharaj/.ssh/id_ed25519"
          ansible_ssh_private_key_file: '/Users/nmaharaj/Documents/ansible/private_key/id_ed25519'
          ansible_python_interpreter: /usr/bin/python
          ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
      vars:
        libs:
          - nc
          - wget
          - openssl-devel
          - git
          - gcc
          - maven
          - bind-utils
          - java-11-openjdk
          - java-11-openjdk-devel
          - cairo-devel
          - pkg-config
          - python3-devel
          - python-firewall
        python_libs:
          - openssl-devel
          - bzip2-devel
          - libffi-devel
          - sqlite-devel
        python_version: 3.12.1
        python_bin_url: https://www.python.org/ftp/python/3.12.1/Python-3.12.1.tgz
        python_bin_name: Python-3.12.1
        python_exec_path: /usr/local/bin/python3.12
        pip_min_dep: packaging
        python_unpacked_dir: /tmp/Python-3.12.1/
        python_download_to_dir: /tmp/
        python_pip_installs_req:
          - meson
          - pycairo
          - bottle
          - SQLAlchemy
        firewall_ports:
          - 6443/tcp
          - 10250/tcp
          - 3000/tcp
          - 3001/tcp
          - 3002/tcp
          - 9145/tcp
          - 8888/tcp
          - 2181/tcp
          - 27027/tcp
          - 28027/tcp
          - 29027/tcp
          - 30027/tcp
          - 31027/tcp
          - 32027/tcp
          - 33027/tcp
          - 34027/tcp
          - 2888/tcp
          - 3888/tcp
          - 9092/tcp
          - 22/tcp
        java_dir_loc: /etc/alternatives/java_sdk_11_openjdk/bin/
        java_dir_link_to: /usr/bin/
        scala_install_loc: /home/nmaharaj/cs-aarch64-pc-linux.gz
        scala_binary: /home/nmaharaj/.local/share/coursier/bin/scala
        scala_download_url_arm: https://github.com/VirtusLab/coursier-m1/releases/latest/download/cs-aarch64-pc-linux.gz
        scala_download_url_amd: https://github.com/coursier/coursier/releases/latest/download/cs-aarch64-pc-linux.gz
        user: nmaharaj
    jenkins:
      hosts:
        broker01:
          ansible_host: broker01
          ansible_ssh_user: nmaharaj
          # Fails on arm
          # ansible_ssh_private_key_file: "/Users/nmaharaj/.ssh/id_ed25519"
          ansible_ssh_private_key_file: '/Users/nmaharaj/Documents/ansible/private_key/id_ed25519'
          ansible_python_interpreter: /usr/bin/python
          ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
      vars:
        libs:
          - fontconfig
          - java-17-openjdk
          - jenkins
          - nc
          - wget
          - git
          - python3-devel
        jenkins_ssl_verify: false
        jenkins_gpg_key_url: "https://pkg.jenkins.io/redhat-stable/jenkins.io.key"
        jenkins_repo_url: "https://pkg.jenkins.io/redhat-stable/jenkins.repo"
        jenkins_repo_dest: /etc/yum.repos.d/jenkins.repo
        jenkins_pwd_show: false # once changed on gui front end pwd file removed
        pip_min_dep: packaging
        python_pip_installs_req:
          - ansible-lint
        firewall_ports:
          - 8080/tcp
    jenkins-node:
      hosts:
        broker02:
          ansible_host: broker02
          ansible_ssh_user: nmaharaj
          # Fails on arm
          # ansible_ssh_private_key_file: "/Users/nmaharaj/.ssh/id_ed25519"
          ansible_ssh_private_key_file: '/Users/nmaharaj/Documents/ansible/private_key/id_ed25519'
          ansible_python_interpreter: /usr/bin/python
          ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
      vars:
        libs:
          - java-17-openjdk
          - nc
          - wget
          - python3-devel
          - git
          - dnf-plugins-core
          - sshpass
        docker_libs:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
          - docker-buildx-plugin 
          - docker-compose-plugin
        pip_min_dep: packaging
        python_pip_installs_req:
          - ansible-lint
        user: nmaharaj
# End
