all:
  vars:
    global:
      hostnames_env:
        - 192.168.56.151 broker01 jenkins
        - 192.168.56.152 broker02 jenkins-node
        - 192.168.56.153 broker03
        - 192.168.56.154 broker04
        - 192.168.56.155 broker05
  children:
    jenkins:
      hosts:
        broker01:
          ansible_host: broker01
          ansible_ssh_user: devops1
          ansible_ssh_private_key_file: private_key
          ansible_python_interpreter: /usr/bin/python
          ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    jenkins_agents:
      hosts:
        broker02:
          ansible_host: broker02
          ansible_ssh_user: devops1
          ansible_ssh_private_key_file: private_key
          ansible_python_interpreter: /usr/bin/python
          ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    deploy_machines:
      hosts:
        broker03:
          ansible_host: broker03
          ansible_ssh_user: "devops1"
          ansible_ssh_private_key_file: private_key
          ansible_private_key_file: /Users/devops1/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python
          ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
        broker04:
          ansible_host: broker04
          ansible_ssh_user: devops1
          ansible_ssh_private_key_file: private_key
          ansible_python_interpreter: /usr/bin/python
          ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
        broker05:
          ansible_host: broker05
          ansible_ssh_user: devops1
          ansible_ssh_private_key_file: private_key
          ansible_python_interpreter: /usr/bin/python
          ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
grafana:
  children:
    jenkins  
