# How to get hosts IP address for each vm
# vmrun getGuestIPAddress /Users/nmaharaj/Virtual\ Machines.localized/broker01.vmwarevm/broker01.vmx
# > 172.16.5.145
all:
  vars:
    global:
  hosts:
    broker01:
      ansible_host: broker01
      ansible_ssh_user: devops1
      ansible_ssh_private_key_file: private_key
      ansible_python_interpreter: /usr/bin/python
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'    
    broker02:
      ansible_host: broker02
      ansible_ssh_user: devops1
      ansible_ssh_private_key_file: private_key
      ansible_python_interpreter: /usr/bin/python
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'   
    broker03:
      ansible_host: broker03
      ansible_ssh_user: "devops1"
      ansible_ssh_private_key_file: private_key
      ansible_private_key_file: /Users/devops1/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    broker04:
      ansible_host: broker04
      ansible_ssh_user: devops1
      ansible_ssh_private_key_file: private_key
      ansible_python_interpreter: /usr/bin/python
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    broker05:
      ansible_host: broker05
      ansible_ssh_user: devops1
      ansible_ssh_private_key_file: private_key
      ansible_python_interpreter: /usr/bin/python
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    broker06:
      ansible_host: broker06
      ansible_ssh_user: devops1
      ansible_ssh_private_key_file: private_key
      ansible_python_interpreter: /usr/bin/python
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
  children:
    web:
      hosts:
        broker01:
    jenkins:
      hosts:
        broker01:
    grafana:
      hosts:
        broker01:
    jenkins_agents:
      hosts:
        broker02:
    deploy_machines:
      hosts:
        broker03:
        broker04:
        broker05:
        broker06:
    all_machines:
      children:
        jenkins:
        jenkins_agents:
        deploy_machines:

        