---
- name: "Deploy Machines Define Roles for MongoDB"
  hosts: deploy_machines
  gather_facts: true
  become: true
  roles:
    - role: "community.mongodb.mongodb_linux"
    # - role: "community.mongodb.mongodb_selinux" ( fails to install arm64 )
    - role: "community.mongodb.mongodb_repository"
      mongodb_version: "6.0"
    - { role: "community.mongodb.mongodb_mongod", sharding: true }
    - role: "shard"
    - role: "replicaset"
