# ansible-playbook -i production deploy_machines.yaml -t tag1,tag2
- name: Retrieve OS Family
  hosts: all
  gather_facts: true  # Ensures that facts are collected

- name: Deploy Machines Define Roles
  hosts: deploy_machines
  roles:
    - common
    - deploy_machines
    - mongodb_install
