# ansible-playbook -i production site.yaml -t tag1,tag2
- name: Import Web Playbook
  ansible.builtin.import_playbook: jenkins.yaml

- name: Import Jenkins Agents Playbook
  ansible.builtin.import_playbook: jenkins_agents.yaml

- name: Import Deploy Machines Playbook
  ansible.builtin.import_playbook: deploy_machines.yaml

# - name: Import Grafana Playbook
#   ansible.builtin.import_playbook: grafana.yaml

# - name: Import Prometheus Playbook
#   ansible.builtin.import_playbook: prometheus.yaml

# - name: Import Sonarqube Playbook
#   ansible.builtin.import_playbook: sonarqube.yaml
