- name: Add MongoDB to yum repo
  ansible.builtin.yum_repository:
    name: mongodb-org-{{ mongodb_version }}
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/{{ mongodb_os }}/{{ mongodb_os_ver}}/mongodb-org/{{ mongodb_version }}/{{ ansible_facts.architecture }}/
    gpgcheck: true
    gpgkey: https://pgp.mongodb.com/server-{{ mongodb_version }}.asc
    enabled: true
  become: true
  tags: mongo_repo
  when: ansible_os_family == "RedHat"
  
# tasks file for mongodb_install
- name: Install MongoDB Packages
  ansible.builtin.package:
    name: "{{ mongodb_install_package }}"
    state: present
  become: true
  tags: mongo_install
  when: ansible_os_family == "RedHat"
