# tasks file for mongodb_install
- name: Install MongoDB Packages
  ansible.builtin.package:
    name: "{{ mongodb_install_package }}"
    state: present
  become: true
  tags: mongo_install
  when: ansible_os_family == "RedHat"
